import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Sparkles, MapPin, ArrowRight, Send, Star, Zap, Shield, Globe } from 'lucide-react';

const TRUST_BADGES = [
  { icon: Zap, label: 'Instant Generation', color: 'text-amber-400' },
  { icon: Globe, label: '50+ Destinations', color: 'text-sky-400' },
  { icon: Shield, label: 'Budget Optimized', color: 'text-emerald-400' },
  { icon: Star, label: '99.4% Satisfaction', color: 'text-violet-400' },
];

export const HeroSection: React.FC = () => {
  const navigate = useNavigate();
  const [quickPrompt, setQuickPrompt] = useState('');

  const handleQuickSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (quickPrompt.trim()) {
      navigate('/plan', { state: { initialPrompt: quickPrompt } });
    } else {
      navigate('/plan');
    }
  };

  const handleChipClick = (destination: string) => {
    navigate('/plan', { state: { initialPrompt: `Plan a 5-day balanced trip to ${destination} for 2 people with $2,000 budget.` } });
  };

  return (
    <section className="relative pt-8 pb-16 lg:pt-12 lg:pb-20 overflow-hidden">
      {/* Decorative elements */}
      <div className="absolute top-10 left-10 w-64 h-64 rounded-full bg-indigo-600/10 blur-[80px] pointer-events-none" />
      <div className="absolute bottom-10 right-10 w-72 h-72 rounded-full bg-purple-600/8 blur-[100px] pointer-events-none" />

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 lg:gap-16 items-center">
        {/* Left Column */}
        <div className="space-y-8">
          {/* Badge */}
          <div className="inline-flex items-center gap-2.5 px-4 py-2 rounded-full border border-indigo-500/30 bg-indigo-500/10 backdrop-blur-sm">
            <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
            <span className="text-xs font-semibold text-indigo-300 tracking-wide">AI-Powered Travel Intelligence</span>
          </div>

          {/* Headline */}
          <div className="space-y-3">
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold tracking-tight leading-[1.08] text-white">
              Plan Smarter.{' '}
              <br />
              <span className="gradient-text">Travel Better.</span>
            </h1>
            <p className="text-slate-400 text-lg leading-relaxed max-w-lg">
              Describe your dream trip and get a complete, day-by-day itinerary with budget breakdowns — generated by AI in seconds.
            </p>
          </div>

          {/* Quick Search */}
          <form onSubmit={handleQuickSubmit} className="space-y-3">
            <div className="relative flex items-center gap-2 p-2 rounded-2xl border border-white/10 bg-white/5 backdrop-blur-md hover:border-indigo-500/40 focus-within:border-indigo-500/50 focus-within:bg-indigo-500/5 transition-all duration-300 shadow-xl">
              <MapPin className="w-5 h-5 text-indigo-400 ml-2 shrink-0" />
              <input
                type="text"
                value={quickPrompt}
                onChange={(e) => setQuickPrompt(e.target.value)}
                placeholder="Where to? e.g. 7 days in Bali for 2 people, $2000..."
                className="flex-1 bg-transparent px-2 py-2.5 text-sm text-white placeholder:text-slate-500 focus:outline-none"
              />
              <button
                type="submit"
                className="btn-primary flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold text-white shrink-0 cursor-pointer"
              >
                <span>Plan Now</span>
                <Send className="w-3.5 h-3.5" />
              </button>
            </div>

            {/* Destination chips */}
            <div className="flex flex-wrap items-center gap-2">
              <span className="text-xs text-slate-600 font-medium">Try:</span>
              {['Tokyo', 'Paris', 'Bali', 'Dubai', 'Swiss Alps', 'New York'].map((dest) => (
                <button
                  key={dest}
                  type="button"
                  onClick={() => handleChipClick(dest)}
                  className="px-3 py-1 rounded-lg bg-white/5 border border-white/8 text-xs text-slate-400 hover:text-white hover:bg-indigo-500/15 hover:border-indigo-500/30 transition-all duration-200 cursor-pointer"
                >
                  {dest}
                </button>
              ))}
            </div>
          </form>

          {/* CTAs */}
          <div className="flex flex-wrap items-center gap-3">
            <Link to="/plan">
              <button className="btn-primary flex items-center gap-2.5 px-6 py-3 rounded-xl text-sm font-semibold text-white cursor-pointer">
                <Sparkles className="w-4 h-4" />
                <span>Full AI Planner</span>
                <ArrowRight className="w-4 h-4" />
              </button>
            </Link>
            <Link to="/itinerary/sample-tokyo-2026">
              <button className="flex items-center gap-2 px-5 py-3 rounded-xl border border-white/12 bg-white/4 text-sm font-medium text-slate-300 hover:text-white hover:bg-white/8 hover:border-white/20 transition-all duration-200 cursor-pointer">
                <span>▶ View Sample Plan</span>
              </button>
            </Link>
          </div>

          {/* Trust Badges */}
          <div className="flex flex-wrap items-center gap-4 pt-2">
            {TRUST_BADGES.map(({ icon: Icon, label, color }) => (
              <div key={label} className="flex items-center gap-1.5 text-xs text-slate-500">
                <Icon className={`w-3.5 h-3.5 ${color}`} />
                <span>{label}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Right Column — Preview Card */}
        <div className="relative lg:pl-8">
          {/* Glow behind card */}
          <div className="absolute inset-0 -m-6 rounded-3xl bg-gradient-to-br from-indigo-600/20 via-purple-600/10 to-transparent blur-3xl" />

          {/* Main preview card */}
          <div className="relative glass-card card-shine rounded-3xl p-6 border border-indigo-500/20 shadow-2xl animate-float">
            {/* Card header */}
            <div className="flex items-start justify-between mb-5">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center shadow-lg shadow-indigo-500/30">
                  <MapPin className="w-5 h-5 text-white" />
                </div>
                <div>
                  <div className="text-sm font-bold text-white">Tokyo 5-Day Expedition</div>
                  <div className="text-xs text-slate-500 mt-0.5">Balanced Style • 2 Travelers</div>
                </div>
              </div>
              <span className="px-2.5 py-1 rounded-full text-[10px] font-bold bg-indigo-500/20 text-indigo-300 border border-indigo-500/30">
                AI Generated
              </span>
            </div>

            {/* Budget bar */}
            <div className="p-3.5 rounded-xl border border-white/8 bg-white/3 mb-4">
              <div className="flex items-center justify-between text-xs">
                <span className="text-slate-400 font-medium">Total Estimated Budget</span>
                <span className="text-emerald-400 font-bold text-sm">$1,850 USD</span>
              </div>
              <div className="mt-2 h-1.5 rounded-full bg-white/10 overflow-hidden">
                <div className="h-full w-[74%] rounded-full bg-gradient-to-r from-emerald-500 to-emerald-400" />
              </div>
            </div>

            {/* Timeline items */}
            <div className="space-y-3 mb-4">
              <div className="text-[10px] font-bold uppercase tracking-widest text-slate-600">Day 1 Highlights</div>
              {[
                { time: '09:00 AM', place: 'Senso-ji Temple & Asakusa', type: 'Culture', color: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30' },
                { time: '01:00 PM', place: 'Shibuya Crossing & Ramen Alley', type: 'Food', color: 'bg-amber-500/20 text-amber-300 border-amber-500/30' },
                { time: '07:00 PM', place: 'Shinjuku Night District', type: 'Nightlife', color: 'bg-purple-500/20 text-purple-300 border-purple-500/30' },
              ].map((item) => (
                <div key={item.time} className="flex items-center gap-3 p-3 rounded-xl bg-white/3 border border-white/6 hover:border-indigo-500/20 transition-colors">
                  <div className="text-[10px] text-slate-600 font-mono w-[62px] shrink-0">{item.time}</div>
                  <div className="flex-1 text-xs font-medium text-slate-200">{item.place}</div>
                  <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full border ${item.color}`}>{item.type}</span>
                </div>
              ))}
            </div>

            {/* Footer */}
            <div className="flex items-center justify-between pt-3 border-t border-white/5 text-[11px]">
              <span className="text-slate-500">Route optimized · 5 days · 17 activities</span>
              <span className="text-indigo-400 font-semibold">99.8% Match</span>
            </div>
          </div>

          {/* Floating stat badges */}
          <div className="absolute -top-4 -right-4 glass-card rounded-2xl px-4 py-3 border border-white/10 shadow-xl animate-fade-in-scale">
            <div className="text-lg font-extrabold text-white">10K+</div>
            <div className="text-[10px] text-slate-500">Trips Generated</div>
          </div>
          <div className="absolute -bottom-4 -left-4 glass-card rounded-2xl px-4 py-3 border border-emerald-500/20 shadow-xl animate-fade-in-scale" style={{ animationDelay: '0.2s' }}>
            <div className="text-lg font-extrabold text-emerald-400">99.4%</div>
            <div className="text-[10px] text-slate-500">Satisfaction</div>
          </div>
        </div>
      </div>
    </section>
  );
};
