import React from 'react';
import { Link } from 'react-router-dom';
import { Compass, Heart, Code2, ExternalLink, AlertTriangle, Bot } from 'lucide-react';
import { APP_CONFIG } from '@/utils/constants';

const LINKS = {
  product: [
    { label: 'Home', to: '/' },
    { label: 'AI Planner', to: '/plan' },
    { label: 'Saved Trips', to: '/saved' },
    { label: 'Demo Itinerary', to: '/itinerary/sample-tokyo-2026' },
  ],
  stack: ['React 19 + TypeScript', 'Vite Build System', 'Tailwind CSS v4', 'Google Gemini Flash', 'Express.js API', 'React Router v7'],
};

export const Footer: React.FC = () => {
  return (
    <footer
      role="contentinfo"
      className="w-full border-t border-white/5 bg-[#060914] pt-14 pb-8 mt-16 relative overflow-hidden"
    >
      {/* Subtle glow */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-40 bg-indigo-600/8 blur-[80px] pointer-events-none" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        {/* AI Disclosure */}
        <div className="mb-12 p-5 rounded-2xl border border-amber-500/15 bg-amber-500/5 flex gap-4 items-start">
          <div className="p-2 rounded-xl bg-amber-500/10 shrink-0 mt-0.5">
            <Bot className="w-4 h-4 text-amber-400" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-amber-300 mb-1.5 flex items-center gap-2">
              <AlertTriangle className="w-3.5 h-3.5" />
              AI-Generated Content Notice
            </h3>
            <p className="text-xs text-slate-500 leading-relaxed max-w-3xl">
              All itineraries are generated by <strong className="text-slate-400">Google Gemini 1.5 Flash</strong>. Prices, timings, and recommendations are AI-estimated and should be verified
              before travel. PlanSmart AI is not responsible for inaccuracies. Always cross-check with official sources and local advisories.
            </p>
          </div>
        </div>

        {/* Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-10 mb-12">
          {/* Brand */}
          <div className="sm:col-span-2 md:col-span-1 space-y-4">
            <Link to="/" className="flex items-center gap-3 group w-fit">
              <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center shadow-md">
                <Compass className="w-4 h-4 text-white" />
              </div>
              <span className="text-base font-bold text-white tracking-tight">
                {APP_CONFIG.appName}
              </span>
            </Link>
            <p className="text-sm text-slate-600 leading-relaxed max-w-[220px]">
              AI-powered travel planning. Complete itineraries in seconds, personalized to your style and budget.
            </p>
            <a
              href="https://github.com/Tejamanoj/plansmart-ai"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-1.5 text-xs text-slate-600 hover:text-slate-300 transition-colors"
            >
              <Code2 className="w-3.5 h-3.5" />
              <span>View Source</span>
              <ExternalLink className="w-3 h-3" />
            </a>
          </div>

          {/* Product */}
          <nav aria-label="Footer product navigation">
            <h4 className="text-[11px] font-bold uppercase tracking-widest text-slate-600 mb-4">Product</h4>
            <ul className="space-y-2.5">
              {LINKS.product.map((link) => (
                <li key={link.to}>
                  <Link to={link.to} className="text-sm text-slate-500 hover:text-slate-200 transition-colors">
                    {link.label}
                  </Link>
                </li>
              ))}
            </ul>
          </nav>

          {/* Stack */}
          <div>
            <h4 className="text-[11px] font-bold uppercase tracking-widest text-slate-600 mb-4">Tech Stack</h4>
            <ul className="space-y-2.5">
              {LINKS.stack.map((item) => (
                <li key={item} className="text-sm text-slate-500">{item}</li>
              ))}
            </ul>
          </div>

          {/* Project */}
          <div>
            <h4 className="text-[11px] font-bold uppercase tracking-widest text-slate-600 mb-4">Project</h4>
            <div className="space-y-3 text-sm text-slate-500">
              <p>Built as an AI Internship Assignment for <strong className="text-slate-400">Flam</strong>.</p>
              <div className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                ✅ All Milestones Complete
              </div>
              <div className="text-xs text-slate-700 space-y-1 pt-2">
                <p>v{APP_CONFIG.version} · MIT License</p>
              </div>
            </div>
          </div>
        </div>

        {/* Bottom */}
        <div className="pt-8 border-t border-white/5 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-slate-700">
          <p>© {new Date().getFullYear()} {APP_CONFIG.appName}. All rights reserved.</p>
          <p className="flex items-center gap-1.5">
            Made with <Heart className="w-3 h-3 text-rose-500 fill-rose-500" /> for smart travel planning
          </p>
        </div>
      </div>
    </footer>
  );
};
