import React from 'react';
import { Link } from 'react-router-dom';
import { Compass, Sparkles, Heart, Bot, AlertCircle, ExternalLink, Code2 } from 'lucide-react';
import { APP_CONFIG } from '@/utils/constants';

/**
 * Footer — site-wide footer.
 *
 * Includes:
 *  - AI transparency/disclosure notice (required for AI-assisted tools)
 *  - Tech stack listing
 *  - Navigation sitemap
 *  - Copyright + credits
 */
export const Footer: React.FC = () => {
  return (
    <footer
      role="contentinfo"
      className="w-full border-t border-slate-800/80 bg-slate-950/90 pt-16 pb-12 mt-20 relative overflow-hidden"
    >
      {/* Background Glow */}
      <div className="gradient-glow top-0 left-1/2 -translate-x-1/2 w-96 h-96 bg-sky-500/10 pointer-events-none" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10 space-y-12">
        {/* ── AI Disclosure Notice ─────────────────────────────────── */}
        <div className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-4 sm:p-6 flex flex-col sm:flex-row gap-4 items-start">
          <div className="shrink-0 p-2 rounded-xl bg-amber-500/10 text-amber-400">
            <Bot className="w-5 h-5" aria-hidden="true" />
          </div>
          <div className="space-y-1.5">
            <h3 className="text-sm font-bold text-amber-300 flex items-center gap-2">
              <AlertCircle className="w-4 h-4" aria-hidden="true" />
              AI-Generated Content Disclosure
            </h3>
            <p className="text-xs text-slate-400 leading-relaxed max-w-2xl">
              Trip itineraries shown in PlanSmart AI are generated by <strong className="text-slate-300">Google Gemini 1.5 Flash</strong>.
              All suggestions—including activity timings, cost estimates, locations, and descriptions—are AI-generated
              and should be independently verified before making any travel commitments. Prices, availability, and
              recommendations may not reflect current real-world conditions.
            </p>
            <p className="text-xs text-amber-400/80">
              ⚠ Always cross-reference with official tourism sites, booking platforms, and local advisories before travelling.
            </p>
          </div>
        </div>

        {/* ── Main Grid ────────────────────────────────────────────── */}
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-8">
          {/* Brand Column */}
          <div className="space-y-4 sm:col-span-2 md:col-span-1">
            <Link to="/" aria-label="PlanSmart AI – Go to homepage" className="flex items-center gap-2.5">
              <div className="p-2 rounded-xl bg-gradient-to-tr from-sky-500 to-indigo-600 text-white shadow-md">
                <Compass className="w-5 h-5" aria-hidden="true" />
              </div>
              <span className="text-lg font-bold text-white tracking-tight flex items-center gap-1">
                {APP_CONFIG.appName}
                <Sparkles className="w-3.5 h-3.5 text-sky-400" aria-hidden="true" />
              </span>
            </Link>
            <p className="text-slate-400 text-sm leading-relaxed">
              AI-powered trip planning engine that creates personalised, budget-aware travel
              itineraries in seconds — powered by Google Gemini 1.5 Flash.
            </p>
            <div className="flex items-center gap-3 pt-1">
              <a
                href="https://github.com/Tejamanoj/plansmart-ai"
                target="_blank"
                rel="noopener noreferrer"
                aria-label="View PlanSmart AI source code on GitHub"
                className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-sky-400 transition-colors"
              >
                <Code2 className="w-4 h-4" aria-hidden="true" />
                <span>GitHub Repo</span>
                <ExternalLink className="w-3 h-3" aria-hidden="true" />
              </a>
            </div>
          </div>

          {/* Navigation Column */}
          <nav aria-label="Footer navigation">
            <h4 className="text-sm font-semibold text-white uppercase tracking-wider mb-3">Navigation</h4>
            <ul className="space-y-2 text-sm text-slate-400">
              <li><Link to="/" className="hover:text-sky-400 transition-colors focus-visible:text-sky-400">Home Page</Link></li>
              <li><Link to="/plan" className="hover:text-sky-400 transition-colors focus-visible:text-sky-400">Plan New Trip</Link></li>
              <li><Link to="/saved" className="hover:text-sky-400 transition-colors focus-visible:text-sky-400">Saved Itineraries</Link></li>
              <li><Link to="/itinerary/sample-tokyo-2026" className="hover:text-sky-400 transition-colors focus-visible:text-sky-400">Demo Trip</Link></li>
            </ul>
          </nav>

          {/* Tech Stack Column */}
          <div>
            <h4 className="text-sm font-semibold text-white uppercase tracking-wider mb-3">Tech Stack</h4>
            <ul className="space-y-2 text-sm text-slate-400">
              <li>React 19 + TypeScript</li>
              <li>Vite 8 Build System</li>
              <li>Tailwind CSS v4</li>
              <li>React Router v7</li>
              <li>dnd-kit (Drag & Drop)</li>
              <li>Google Gemini 1.5 Flash</li>
              <li>Express.js Backend</li>
            </ul>
          </div>

          {/* Project Info Column */}
          <div>
            <h4 className="text-sm font-semibold text-white uppercase tracking-wider mb-3">Project Info</h4>
            <div className="space-y-3 text-sm text-slate-400">
              <p>Built as a Frontend AI Internship Assignment for <strong className="text-slate-300">Flam</strong>.</p>
              <div className="space-y-1.5">
                <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                  <span>✅ All Milestones Complete</span>
                </div>
              </div>
              <div className="pt-1 space-y-1 text-xs text-slate-500">
                <p>v{APP_CONFIG.version} — Production Build</p>
                <p>MIT License</p>
              </div>
            </div>
          </div>
        </div>

        {/* ── Bottom Bar ───────────────────────────────────────────── */}
        <div className="pt-8 border-t border-slate-800/80 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-slate-500">
          <p>© {new Date().getFullYear()} {APP_CONFIG.appName}. All rights reserved.</p>
          <p className="flex items-center gap-1.5">
            Engineered with <Heart className="w-3.5 h-3.5 text-rose-500 fill-rose-500" aria-hidden="true" /> for AI Trip Planning
          </p>
        </div>
      </div>
    </footer>
  );
};
